version: '3.8'

services:
  back_end:
    build:
      context: .
      dockerfile: Dockerfile
    image: sydwellcbu/student_portal:0.0.1-SNAPSHOT
    container_name: student-portal-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/student_portal
      SPRING_DATASOURCE_USERNAME: student_user
      SPRING_DATASOURCE_PASSWORD: student_pass

      SPRING_MAIL_HOST: maildev
      SPRING_MAIL_PORT: 1025
      SPRING_MAIL_USERNAME: null
      SPRING_MAIL_PASSWORD: null
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: false
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: false

      CLIENT_HOST:
      CLIENT_PORT:
    depends_on:
      - mysql_db
      - maildev
    networks:
      - app-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/auth/test"]
      interval: 30s
      timeout: 10s
      retries: 5

  front_end:
    build:
      context: .
      dockerfile: Dockerfile
    image: sydwellcbu/student_portal_ui:0.0.1-SNAPSHOT
    container_name: student-portal-ui-container
    ports:
      - "4200:4200"
    depends_on:
      - back_end
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  mysql_db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: student_portal
      MYSQL_USER: student_user
      MYSQL_PASSWORD: student_pass
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p rootpassword || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  maildev:
    image: maildev/maildev
    container_name: maildev-container
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1025"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local