auth_enabled: false
server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  http_server_read_timeout: 300s
  http_server_write_timeout: 300s
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  log_level: info
  log_format: json

common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
    heartbeat_timeout: 1m

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h
    resync_interval: 5m
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks
  tsdb_shipper:
    active_index_directory: /loki/tsdb-index
    cache_location: /loki/tsdb-cache
    cache_ttl: 24h

limits_config:
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  max_streams_per_user: 10000
  max_streams_matchers_per_query: 1000
  max_global_streams_per_user: 0
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  creation_grace_period: 2h
  retention_period: 720h
  max_query_series: 5000
  max_query_parallelism: 32
  max_query_length: 721h
  per_stream_rate_limit: 10MB
  per_stream_rate_limit_burst: 20MB

query_range:
  align_queries_with_step: true
  max_retries: 5
  cache_results: true
  results_cache:
    cache:
      enable_fifocache: true
      fifocache:
        max_size_bytes: 256MB
        validity: 1h

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  retention_enabled: true
  compaction_interval: 10m
  retention_delete_delay: 2h
  retention_delete_worker_count: 10

table_manager:
  retention_deletes_enabled: true
  retention_period: 720h
  poll_interval: 5m
  creation_grace_period: 2h

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: http://alertmanager:9093
  ring:
    kvstore:
      store: inmemory
  evaluation_interval: 1m
  poll_interval: 1m
  enable_api: true

frontend:
  max_outstanding_per_tenant: 100
  log_queries_longer_than: 10s

frontend_worker:
  match_max_concurrent: true

ingester:
  lifecycler:
    ring:
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 30m
  chunk_block_size: 262144
  chunk_retain_period: 5m
  max_transfer_retries: 0
  wal:
    enabled: true
    dir: /loki/wal
    replay_memory_ceiling: 4GB

querier:
  query_ingesters_within: 3h
  engine:
    timeout: 3m
    max_look_back_period: 0s