server:
  port: 8083
  servlet:
    context-path: /api/v1
# url: jdbc:mysql://mysql-container:3306/student_portal # Connect to the MySQL container by service name when running app the in a container

spring:
  application:
    name: Student Portal
  datasource:
    url: jdbc:mysql://localhost:3306/student_portal?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: student_user
    password: student_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

    jpa:
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true

    flyway:
      enabled: true
      baseline-on-migrate: true
      locations: classpath:db/migration

  mysql:
    continue-on-error: true
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

  mail:
    protocol: smtp
    host: ${MAIL_HOST:localhost}
    port: 1025
    properties:
      mail:
        transport:
          protocol: smtps
        smtp:
          auth: false
          starttls:
            enable: true
    username:
    password:
    default-encoding: utf-8
    test-connection: true


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    check-template-location: true

springdoc:
  swagger-ui:
    path: /swagger-ui
    config-url: /api/v1/v3/api-docs/swagger-config
    url: /api/v1/v3/api-docs
  api-docs:
    path: /v3/api-docs

student-portal:
  host: ${CLIENT_HOST:localhost}:${CLIENT_PORT:4200}
  jwtSecret: ByCoZ1VLVlASquaddedKt152JBTcC41Tdh


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true

