server:
  port: 8083
  servlet:
    context-path: /api/v1

spring:
  application:
    name: Student Portal

  datasource:
    url: jdbc:mysql://localhost:3306/student_portal?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: student_user
    password: student_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  mail:
    protocol: smtp
    host: ${MAIL_HOST:localhost}
    port: 1025
    username: ""  # explicitly blank
    password: ""  # explicitly blank
    default-encoding: utf-8
    test-connection: true
    properties:
      mail:
        transport:
          protocol: smtps
        smtp:
          auth: false
          starttls:
            enable: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    check-template-location: true

springdoc:
  swagger-ui:
    path: /swagger-ui
    config-url: /api/v1/v3/api-docs/swagger-config
    url: /api/v1/v3/api-docs
  api-docs:
    path: /v3/api-docs

student-portal:
  host: ${CLIENT_HOST:localhost}:${CLIENT_PORT:4200}
  jwtSecret: ByCoZ1VLVlASquaddedKt152JBTcC41Tdh

management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true

logging:
  file:
    name: /var/log/spring-boot-app/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework: INFO
    com.your.package: INFO