version: '3.8'

services:
  student-portal:
    build:
      context: ..
      dockerfile: Dockerfile
    image: sydwellcbu/student_portal:0.0.1-SNAPSHOT
    container_name: student-portal
    restart: unless-stopped
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/student_portal
      SPRING_DATASOURCE_USERNAME: student_user
      SPRING_DATASOURCE_PASSWORD: student_pass
      SPRING_MAIL_HOST: maildev
      SPRING_MAIL_PORT: "1025"
      SPRING_MAIL_USERNAME: ""
      SPRING_MAIL_PASSWORD: ""
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "false"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "false"
      CLIENT_HOST: ""
    depends_on:
      - mysql-db
      - maildev
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8083/api/v1/actuator/health"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 60s

  student-portal-ui:
    image: sydwellcbu/student_portal_ui:0.0.1-SNAPSHOT
    container_name: student-portal-ui
    restart: unless-stopped
    ports:
      - "4200:4200"
      - "9113:9113"
    depends_on:
      - student-portal
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 30s

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: student_portal
      MYSQL_USER: student_user
      MYSQL_PASSWORD: student_pass
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 5G
        reservations:
          cpus: '0.5'
          memory: 1G
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 30s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  maildev:
    image: maildev/maildev
    container_name: maildev
    restart: unless-stopped
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1025"]
      interval: 20s
      timeout: 5s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  blackbox-exporter:
    image: prom/blackbox-exporter
    container_name: blackbox-exporter
    restart: unless-stopped
    ports:
      - "9115:9115"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9115"]
      interval: 20s
      timeout: 5s
      retries: 3

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.100.0/24"
          gateway: "192.168.100.1"
          ip_range: "192.168.100.128/25"
          aux_addresses:
            host1: "192.168.100.10"
            host2: "192.168.100.11"
    enable_ipv6: true
    internal: false
    attachable: true

volumes:
  mysql_data:
    driver: local
