# monitoring/prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'student-portal'
    replica: 'prometheus-1'

rule_files:
  - "/etc/prometheus/alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: '/metrics'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']
    scrape_interval: 30s            # Default: 1m (adjust based on needs)
    scrape_timeout: 25s             # Default: 10s (keep < scrape_interval)
    metrics_path: '/metrics'        # Default (explicit for clarity)
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'node_exporter:9100'  # Fixes DNS resolution in Docker
    metric_relabel_configs:
      - regex: '(node_filesystem_avail_bytes|node_filesystem_size_bytes)'
        action: keep                # Only keep critical filesystem metrics
      - regex: '^(node_network_(receive|transmit)_bytes_total|node_cpu_seconds_total)'
        action: keep                # Keep key network/CPU metrics

  # MySQL Exporter - Database metrics
  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['mysql-exporter:9104']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Nginx Exporter - Web server metrics
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9114']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Spring Boot Application - Backend metrics
  - job_name: 'student-portal-backend'
    static_configs:
      - targets: ['student-portal-container:8083']
    scrape_interval: 15s
    metrics_path: '/api/v1/actuator/prometheus'

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    scrape_interval: 15s
    metrics_path: '/metrics'

  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Blackbox Exporter - Endpoint monitoring
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://student-portal-container:8083/api/v1/actuator/health
          - http://student-portal-ui-container:4200
          - http://maildev:1080
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # VictoriaMetrics - Time series database metrics
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8428']
    scrape_interval: 15s
    metrics_path: '/metrics'

remote_write:
  - url: http://victoriametrics:8428/api/v1/write
    queue_config:
      max_samples_per_send: 10000
      batch_send_deadline: 5s
      max_shards: 20